### ISSUE TITLE
Install instructions?

### ISSUE THREAD

**Issue by pvanheus** [arunisaac/ccwl#1]
Please provide instructions on how to build and install ccwl.

Thank you.

**Comment by arunisaac** [comment]
Thanks for the bug report! I just added installation instructions to `README.org`. Let me know if something is not clear. Thanks!

**Comment by arunisaac** [comment]
I have submitted a patch to add ccwl to Guix upstream. See
https://issues.guix.gnu.org/52091 . Once that is accepted, it should be
easier to install ccwl.

**Comment by arunisaac** [comment]
I just added installation instructions using software bundles such as Docker. See https://github.com/arunisaac/ccwl#using-binary-software-bundles Hope that helps with the installation situation!

**Comment by pvanheus** [comment]
Thanks - is the Dockerfile for building the Docker image around somewhere?

**Comment by arunisaac** [comment]
I built the docker image and the tarball pack using Guix itself. I added the commands to do so to the `Makefile` in 5bdb24c18b5d6abed13ad004325b1bf66eaeca74. Docker images built this way using Guix are fully reproducible.

**Comment by arunisaac** [comment]
I guess this issue has been addressed. Closing now..

Also, the ccwl package has now been accepted into Guix.
