### ISSUE TITLE
missing `./bootstrap` file

### ISSUE THREAD

**Issue by zimoun** [arunisaac/ccwl#5]
Hi Arun,

In the section Manually from source, one reads:

```bash
$ ./bootstrap.sh
$ ./configure; make; make install
```

but the file `bootstrap` is not in the repository.  Is it on purpose?

**Comment by arunisaac** [comment]
Hi zimoun! Oops, sorry, the bootstrap step is deprecated. We moved
away from the autotools build system but forgot to update the build
instructions. Fixed in 658925fd83b99faf6ba523e675c3d2dfa8b01714.
