### ISSUE TITLE
Is there any solution for multiple ccwl files?

### ISSUE THREAD

**Issue by ROCKTAKEY** [arunisaac/ccwl#6]
Hi, thanks for your maintenance. This is pretty better than raw cwl.

I would like to use multiple ccwl files and import `command` or `workflow` object to a ccwl file from another ccwl file. Is it possible? Or just `cwl-workflow`is recommended?

**Comment by arunisaac** [comment]
Hi, thank you for your interest in ccwl!

ccwl files are just regular scheme files. So, you can use `load` to combine multiple ccwl files. For example, you can have a `foo.scm` with
```scheme
(define foo
  (command ...))
```
and a `bar.scm` with
```scheme
(define bar
  (command ...))
```
and combine them in another file with
```scheme
(load "foo.scm")
(load "bar.scm")

(workflow (...)
  (pipe (foo ...)
        (bar ...)))
```

**Comment by ROCKTAKEY** [comment]
Thanks! Is it possible to reuse workflow, too?

**Comment by arunisaac** [comment]
Workflows are regular scheme objects just like commands are. So, it is possible to have a `foo.scm` with the following
```scheme
(define foo-command
  (command ...))

(define foo-workflow
  (workflow ...))
```
and reference that in a different file like so:
```scheme
(load "foo.scm")

foo-workflow
```

But, it is not yet possible to put workflow objects into the `pipe` and `tee` constructs. PRs in that direction are welcome.

**Comment by ROCKTAKEY** [comment]
I got it. Thanks!

**Comment by arunisaac** [comment]
With 299a60b666e64df20f1c7065b58aa43e163caae9, it is now possible to
recursively put workflow objects into the pipe and tee constructs.
