### ISSUE TITLE
Passing a constant value as an argument of command causes error

### ISSUE THREAD

**Issue by ROCKTAKEY** [arunisaac/ccwl#7]
I would like to use an existing command or workflow with constant argument like:
```scheme
(define print
  (command #:inputs (message #:type string)
           #:run "echo" message
           #:outputs (printed-message #:type stdout)))

(workflow ()
  (print #:message "Hello"))
```
but it causes error:
```
ccwl/ccwl.scm:396:22: ccwl step `print' supplied with unknown key `"Hello"'. Known keys at this step are `()'.
```

It seems that all values on the command arguments are regarded as symbol which should be corresponding to former output or workflow input.

Is it possible to pass constant value as command argument?

**Comment by arunisaac** [comment]
With 17a76711d1f9bdaad133c9364a9bfd2ef10b8f22, we now have support for
literal values as arguments. I have tested it with literal strings, but
more thorough testing for other types would be good.

**Comment by arunisaac** [comment]
The present implementation works by stuffing literals into the default
values of commands (this is done purely functionally without mutating
the original command object). This is admittedly a little clumsy, but
was the easiest way I could think of to fit this into CWL. Ideas for
better approaches are welcome.

**Comment by ROCKTAKEY** [comment]
Worked fine! Thanks!

I saw the url below, and I think putting value as "default" seems to be better solution, too. (Since I am not so familiar with CWL, I don't know it is best).
https://www.commonwl.org/v1.2/Workflow.html#WorkflowStepInput

If it is possible, another solution is that creating step which takes no inputs and returns constant value.

**Comment by arunisaac** [comment]
> If it is possible, another solution is that creating step which takes
> no inputs and returns constant value.

Yes, that's possible too. But, it's a bit more complicated to pull off,
and the default hack seems to work. We can revisit this if it causes
trouble later.

Cheers!
